# Generated by Django 6.0.3 on 2026-04-23 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_points", "0008_usermapmarker_usermapmarkercomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappoint",
            name="marker_color",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be in #RRGGBB format.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="mappointcategory",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be in #RRGGBB format.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
    ]
