# Generated by Codex on 2026-04-25

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usersocialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_position_x",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_position_y",
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_scale",
            field=models.DecimalField(decimal_places=2, default=Decimal("1.00"), max_digits=3),
        ),
        migrations.AddField(
            model_name="user",
            name="max_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="usersocialaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("vk", "VK"),
                    ("google", "Google"),
                    ("yandex", "Yandex"),
                    ("telegram", "Telegram"),
                ],
                max_length=24,
            ),
        ),
    ]
