# Generated by Django 6.0.3 on 2026-04-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_points', '0008_usermapmarker_usermapmarkercomment_and_more'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreport',
            name='user_marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='map_points.usermapmarker'),
        ),
        migrations.AddField(
            model_name='contentreport',
            name='user_marker_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='map_points.usermapmarkercomment'),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('map_review', 'Map review'), ('user_marker', 'User marker'), ('user_marker_comment', 'User marker comment')], max_length=24),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('support', 'Support'), ('bot', 'Bot'), ('system', 'System')], max_length=16),
        ),
    ]
