# Generated by Codex on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_personal_data_consent_accepted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSocialAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("vk", "VK"), ("google", "Google"), ("yandex", "Yandex")],
                        max_length=24,
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=190)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=190)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="usersocialaccount",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_user_id"),
                name="unique_social_provider_user",
            ),
        ),
    ]
