# Generated by Django 6.0.3 on 2026-08-27 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_validation_avatar_crop_and_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhoneVerificationChallenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('password_reset', 'Password reset')], max_length=32)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('call', 'Код в номере'), ('receive', 'Обратный звонок')], max_length=16)),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('greensms_request_id', models.CharField(blank=True, max_length=64)),
                ('receive_number', models.CharField(blank=True, max_length=32)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verify_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'purpose', 'created_at'], name='users_phone_phone_488c53_idx'), models.Index(fields=['client_ip', 'created_at'], name='users_phone_client__3d033e_idx')],
            },
        ),
    ]
