# Generated by Django 6.0.3 on 2026-08-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_phone_verification_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverificationchallenge',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='phoneverificationchallenge',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('call', 'Код в номере'), ('receive', 'Обратный звонок'), ('email', 'Код на почту')], max_length=16),
        ),
        migrations.AlterField(
            model_name='phoneverificationchallenge',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='phoneverificationchallenge',
            name='purpose',
            field=models.CharField(choices=[('auth', 'Auth'), ('register', 'Register'), ('login', 'Login'), ('password_reset', 'Password reset')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='phoneverificationchallenge',
            index=models.Index(fields=['email', 'purpose', 'created_at'], name='users_phone_email_5f5ced_idx'),
        ),
    ]
